In [1]:
import pandas as pd

Quelques questions : 

- chef de projet web : tech ?
- multimédia ?
- designer graphique ? web designer ? web design ?

In [16]:
!pip3 install unidecode

Collecting unidecode
  Downloading Unidecode-1.2.0-py2.py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 3.5 MB/s eta 0:00:01
Installing collected packages: unidecode
Successfully installed unidecode-1.2.0

In [17]:
import unidecode

https://helenely.com/2021/03/02/ressources-pour-recruteurs-techs/

https://devskiller.com/glossary-it-terms-tech-recruiters/

https://github.com/rootstrap/ai-job-title-area-classification

- constituer un dataset d'évaluation (afin d'évaluer le mapping) - la labellisation sera effectuée à la mano T_T
- constituer un dictionnaire / une liste mapping les termes associés aux profils tech 

- sur le dictionnaire de profils tech : utiliser aussi langages, frameworks, ...

- léger cleaning à effectuer : virer les accents, homogénéiser majuscule/minuscule, virer les lignes qui ne contiennent pas de caractères, ...

- essayer de scrapper vocabulaire tech pour se constituer la liste de mots tech (plutôt que de le faire à la mano)

v1 - implémentation d'une règle logique :
-> si mot in title appartient à map_tech:
        job_title -> tech
   elif juste "ingénieur", "administrateur", ...
       job_title -> incertain
   else:
       pas tech

In [5]:
ls ../domain_classification/data/

Titres_profils.csv

In [101]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [30]:
map_tech = {
    'tech' : [
        'data', 
        'developpeur',
        'it',
        'web',
        'front',
        'fullstack',
        'software',
        'tech',
        'cto',
        'cyber',
        'devops',
        'sysadmin',
        'sre',
        'cloud',
        'qa',
        'ux',
        'ui',
        'postgre',
        'ml',
        'ops',
        'java',
        'python',
        'javascript',
        'azure',
        'gcp',
        'aws',
        'linux'
    ]
}

In [42]:
lst_tech = ['data', 
        'developpeur',
        'it',
        'web',
        'front',
        'fullstack',
        'software',
        'tech',
        'cto',
        'cyber',
        'devops',
        'sysadmin',
        'sre',
        'cloud',
        'qa',
        'ux',
        'ui',
        'postgre',
        'ml',
        'ops',
        'java',
        'python',
        'javascript',
        'azure',
        'gcp',
        'aws',
        'linux']

In [7]:
df = pd.read_csv('../domain_classification/data/Titres_profils.csv')

In [8]:
df.shape

(79991, 1)

In [10]:
df

                                                   Titre
0                          Ingénieur systèmes et réseaux
1                                        Étudiant à ESGI
2      Développeur avec un an d'expérience, je suis à...
3              Ingénieur BIM Principale chez Léon Grosse
4                          Ingénieur Systèmes et Réseaux
...                                                  ...
79986                           Consultante Test Recette
79987                    Développeur chez NETLOR CONCEPT
79988                         Informaticien chez Mercier
79989                 -médecine traditionnelle chinoise-
79990                 Web Marketing Assistant at 1789.fr

[79991 rows x 1 columns]

In [13]:
# lowercase all job title
df['Titre'] = df.Titre.str.lower()

In [24]:
# remove accents
def remove_accents(a):
    return unidecode.unidecode(str(a))

df['Titre'] = df['Titre'].apply(remove_accents)

In [31]:
df

                                                   Titre
0                          ingenieur systemes et reseaux
1                                        etudiant a esgi
2      developpeur avec un an d'experience, je suis a...
3              ingenieur bim principale chez leon grosse
4                          ingenieur systemes et reseaux
...                                                  ...
79986                           consultante test recette
79987                    developpeur chez netlor concept
79988                         informaticien chez mercier
79989                 -medecine traditionnelle chinoise-
79990                 web marketing assistant at 1789.fr

[79991 rows x 1 columns]

In [40]:
type(map_tech.values())

dict_values

In [43]:
for value in map_tech.values():
    print(value)

['data', 'developpeur', 'it', 'web', 'front', 'fullstack', 'software', 'tech', 'cto', 'cyber', 'devops', 'sysadmin', 'sre', 'cloud', 'qa', 'ux', 'ui', 'postgre', 'ml', 'ops', 'java', 'python', 'javascript', 'azure', 'gcp', 'aws', 'linux']

In [60]:
list(map_tech.values())[0]

['data',
 'developpeur',
 'it',
 'web',
 'front',
 'fullstack',
 'software',
 'tech',
 'cto',
 'cyber',
 'devops',
 'sysadmin',
 'sre',
 'cloud',
 'qa',
 'ux',
 'ui',
 'postgre',
 'ml',
 'ops',
 'java',
 'python',
 'javascript',
 'azure',
 'gcp',
 'aws',
 'linux']

In [63]:
df['label'] = df['Titre'].str.contains('|'.join(list(map_tech.values())[0]))

In [68]:
df['Titre'].str.contains('|'.join(lst_tech))

0         True
1        False
2         True
3        False
4         True
         ...
79986    False
79987     True
79988    False
79989     True
79990     True
Name: Titre, Length: 79991, dtype: bool

In [102]:
df[-100:]

                                                   Titre  label
79891               responsable de magasin chez aeroflex  False
79892             data scientist 360deg at digital brain   True
79893  responsable d'exploitation chez bpo brun pergu...   True
79894                        technicien btp chez lodibob   True
79895  directeur de secteur chez saint-gobain distrib...  False
79896                        architecte si chez maif vie   True
79897              technicien automobile / chef d'equipe   True
79898                     technicien chez sarl hydr'auto   True
79899                            gerant chez ebenessence  False
79900        technicien bureau d'etudes - structure bois   True
79901                   gerante meubles lafite, molieres   True
79902                                   ----------------  False
79903             concepteur developpeur web et logiciel   True
79904               responsable marketing chez technilat   True
79905    d.a. / graphiste / motion designer - free-lance  False
79906                              . chez cuisines aviva   True
79907  directeur de la creation, fondateur associe ch...  False
79908           concepteur vendeur chez cuisines schmidt   True
79909                                         cuisiniste   True
79910                     charge de recherches chez inra  False
79911                        decoratrice chez free lance  False
79912                             informaticien chez hth  False
79913                                      sales manager  False
79914                                           designer  False
79915                  repreneur, createur d'entreprises  False
79916  chef de projet as400 - suivi applicatif et dev...   True
79917  ingenieur de production chez dxc technology fr...   True
79918                          programmation chez airbus  False
79919                             pmo projet chez idemia  False
79920             chargee de mission chez maison moderne  False
79921            head of programming chez maison moderne  False
79922            junior art director chez maison moderne   True
79923  event manager - maison moderne independant pub...  False
79924                 conseillere en immobilier chez iad  False
79925   directeur paperjam business club, hec paris emba  False
79926                   studio manager at maison moderne  False
79927  ceo - partner et global c-level executive - bu...  False
79928        senior account manager (print-digital-club)   True
79929       editorial client manager chez maison moderne   True
79930  assistante commerciale & marketing chez maison...  False
79931  art director for terrible people magazine and ...   True
79932                       it manager at maison moderne   True
79933                     art director at maison moderne   True
79934  hr manager - maison moderne independent publis...  False
79935  professeur d'histoire geographie en lycee chez...  False
79936                 formateur chez xpo logistics, inc.  False
79937  chef d'agence chez saint-gobain distribution b...  False
79938  conception du projet sevent chez sevent applic...  False
79939                president de la republique at monde  False
79940  retraite chez auc - school of continuing educa...   True
79941              comptable principal chez navarre auto  False
79942                     commercial chez servi couleurs  False
79943            responsable de magasin chez arrouze sas  False
79944  etudiant a epitech - european institute of tec...   True
79945  responsable de la communication du musee chez ...  False
79946                      head of finance at puy du fou  False
79947  co-fondateur et directeur general de demotivat...  False
79948    administrateur systemes et reseaux chez sofaxis   True
79949  analyste - financement de projet et investisse...  False
79950                   responsable agence chez hexa-net  False
79951  technicien de maintenance mecanique chez arcel...   True
79952           ceo & cofounder @ ekoha - startup studio  False
79953  sdr pour airbus helicopters chez arial industries  False
79954                responsable technique & pedagogique   True
79955  adjoint responsable de production finition pla...   True
79956  stagiaire robotique aeronautique pour airbus h...   True
79957                            ingenieur cybersecurite   True
79958  alternant en master materiaux plastiques et ec...   True
79959                     etudiant a iut d'aix-marseille  False
79960  developpeur - projet manager junior conseil taker   True
79961                  directeur associe de human coders  False
79962                 directeur magasin schmidt paris 10  False
79963     technicien ordonnancement chez noxi agencement   True
79964                         consultant fonctionnel sap  False
79965  chef de projet technique - team leader evol ae...   True
79966                     ingenieur devops chez generali   True
79967                          java consultant chez soat   True
79968  manager de transition it - \n directeur de pro...   True
79969     global partnership director at virtual beehive   True
79970                     chef de projet / consultant bi  False
79971                        senior leader chez onepoint  False
79972                    founder president chez bfi-tech   True
79973  responsable marketing et commercial - membre d...   True
79974  charge de projet numerique chez open digital e...   True
79975  project manager java j2ee au ministere de l'in...   True
79976       directeur de mission chez generation conseil  False
79977              senior consultant chez dxc technology   True
79978  it senior consultant - blockchain solution eng...   True
79979               retired consulting practice director   True
79980               responsable commerciale chez vertego  False
79981  double activite professionnelle : coach profes...   True
79982                                         qa analyst   True
79983                                    qa test manager   True
79984  consultant qualification logicielle / rpa chez...   True
79985            quality assurance lead en mediarithmics   True
79986                           consultante test recette  False
79987                    developpeur chez netlor concept   True
79988                         informaticien chez mercier  False
79989                 -medecine traditionnelle chinoise-   True
79990                 web marketing assistant at 1789.fr   True

In [76]:
for i in range(0, len(df)):
    for value in lst_tech:
        if value in df['Titre'][i:i+1]:
            print('tech')

KeyboardInterrupt:

In [77]:
df['Titre'][0:1]

0    ingenieur systemes et reseaux
Name: Titre, dtype: object

In [71]:
len(df)

79991

In [86]:
df['Titre'].isin(lst_tech)

0        False
1        False
2        False
3        False
4        False
         ...
79986    False
79987    False
79988    False
79989    False
79990    False
Name: Titre, Length: 79991, dtype: bool

SCRAPPING

In [92]:
from bs4 import BeautifulSoup
import urllib.request
import csv

In [93]:
# specify the url
urlpage = 'https://coders.bluecoders.com/jobs'

In [94]:
# query the website and return the html to the variable 'page'
page = urllib.request.urlopen(urlpage)
# parse the html using beautiful soup and store in variable 'soup'
soup = BeautifulSoup(page, 'html.parser')

In [95]:
print(soup)

<!DOCTYPE html>
<html lang="en"><head><base href="/coders/"/><meta charset="utf-8"/><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta content="width=device-width,initial-scale=1" name="viewport"/><link href="/favicon.png" rel="icon"/><title>Coders | Bluecoders</title><link href="/css/chunk-061c7272.495b78f2.css" rel="prefetch"/><link href="/css/chunk-0f2d5674.643de83c.css" rel="prefetch"/><link href="/css/chunk-227d0bf6.68984ce0.css" rel="prefetch"/><link href="/css/chunk-5e627438.9db6f935.css" rel="prefetch"/><link href="/css/chunk-7e674130.414bbce2.css" rel="prefetch"/><link href="/css/chunk-c02b4542.82970b4f.css" rel="prefetch"/><link href="/js/chunk-061c7272.a07d0d15.js" rel="prefetch"/><link href="/js/chunk-0f2d5674.2e6bac87.js" rel="prefetch"/><link href="/js/chunk-227d0bf6.0acd8906.js" rel="prefetch"/><link href="/js/chunk-2d0c5377.a817ff49.js" rel="prefetch"/><link href="/js/chunk-5e627438.5124c77f.js" rel="prefetch"/><link href="/js/chunk-7e674130.f62869a2.js" rel="prefetch"/><link href="/js/chunk-c02b4542.09cfc2b3.js" rel="prefetch"/><link as="style" href="/css/app.99444041.css" rel="preload"/><link as="script" href="/js/app.a6fd83b7.js" rel="preload"/><link as="script" href="/js/chunk-vendors.8e7d0d86.js" rel="preload"/><link href="/css/app.99444041.css" rel="stylesheet"/></head><body><noscript><strong>We're sorry but Coders doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id="app"></div><script src="/js/chunk-vendors.8e7d0d86.js"></script><script src="/js/app.a6fd83b7.js"></script></body></html>

In [97]:
# find results within table
table = soup.find('table', attrs={'class': 'class="jobs col-xs-12"'})

In [99]:
table.find_all('tag card-informations__tag tag--blue-light')

AttributeError: 'NoneType' object has no attribute 'find_all'